name: Hitmplugin
version: '${version}'
main: at.hitm.hitmplugin.Main
api-version: 1.17
authors: [ mPuchner, jHofer ]
description: A plugin for the hitm mc server

commands:
  date:
    description: Zeigt das Datum an
    #usage: /date
  getOnlinePlayers:
    description: Zeigt alle Spieler an die gerade online sind
    #usage: /getOnlinePlayers
  giveMoney:
    description: gives money to a user
    #usage: /givemoney [amount of money]
  warp:
    description: Warps you to a specific location
    usage: /warp [warp name]
  warps:
    usage: /warps <create | delete | info> <warp name>
  givecustomitems:
    description: Gives you all custom items
    permission: op